version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ledger_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        expose:
            - 9000
        depends_on:
            - db
        environment:
            DATABASE_URL: "pgsql://symfony:symfony@db:5432/ledger"

    db:
        image: postgres:15-alpine
        container_name: ledger_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ledger
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: symfony
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data

    nginx:
        image: nginx:stable-alpine
        container_name: ledger_nginx
        ports:
            - 8080:80
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    postgres_data:
