parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    App\EventListener\RateLimitListener:
        arguments:
            $apiLimiter: '@limiter.api_limit'
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 100 }